# Generated by Django 2.2.10 on 2020-03-01 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0009_auto_20200301_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, verbose_name='이메일 주소')),
                ('token', models.CharField(max_length=254, verbose_name='토큰')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MailingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_histories', to='mailings.Mailing')),
                ('stores', models.ManyToManyField(to='stores.Store')),
            ],
        ),
    ]
