# Generated by Django 2.2.10 on 2020-03-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='이메일 주소'),
        ),
    ]
