# Generated by Django 2.2.10 on 2020-03-01 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_auto_20200301_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinghistory',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailing_histories', to='mailings.Mailing'),
        ),
    ]
