# Generated by Django 2.2.10 on 2020-02-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('product_title', models.CharField(max_length=300)),
                ('mall_title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=3, max_digits=13, verbose_name='낱개당 평균 가격')),
                ('product_url', models.URLField(verbose_name='상품 정보 URL')),
                ('in_stock', models.BooleanField(default=False, verbose_name='현재 재고 여부')),
                ('recent_in_stock_date', models.DateTimeField(blank=True, null=True, verbose_name='최근 재고들어온 시간')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='상품 이미지 URL')),
                ('crawling_type', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
