# Generated by Django 2.2.10 on 2020-02-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='store',
            name='now_in_stock',
            field=models.BooleanField(default=False, verbose_name='현재 재고 있는지'),
        ),
        migrations.AlterField(
            model_name='store',
            name='crawling_type',
            field=models.CharField(max_length=50, verbose_name='크롤링 유형(id)'),
        ),
        migrations.AlterField(
            model_name='store',
            name='mall_title',
            field=models.CharField(max_length=100, verbose_name='쇼핑몰 이름'),
        ),
        migrations.AlterField(
            model_name='store',
            name='product_title',
            field=models.CharField(max_length=300, verbose_name='상품명'),
        ),
    ]
