# Generated by Django 2.2.10 on 2020-02-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20200226_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='페이지 공개 여부'),
        ),
    ]
