# Generated by Django 2.2.10 on 2020-02-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='crawling_type',
            field=models.CharField(max_length=50, verbose_name='크롤링 유형'),
        ),
    ]
