# Generated by Django 2.2.10 on 2020-02-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20200226_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='mask_type',
            field=models.CharField(blank=True, choices=[('N95', 'N95'), ('KF99', 'KF99'), ('KF94', 'KF94'), ('KF80', 'KF80'), ('면', '면'), ('천', '천'), ('기타', '기타')], max_length=50, null=True, verbose_name='마스크 종류'),
        ),
        migrations.AddField(
            model_name='store',
            name='size',
            field=models.CharField(blank=True, choices=[('소형', '소형'), ('중형', '중형'), ('대형', '대형'), ('기타', '기타')], max_length=50, null=True, verbose_name='마스크 사이즈'),
        ),
    ]
