# Generated by Django 2.2.10 on 2020-02-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_auto_20200227_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='마스크 사이즈'),
        ),
    ]
