# Generated by Django 2.2.10 on 2020-02-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_stockhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhistory',
            name='modified_at',
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
