# Generated by Django 2.2.10 on 2020-03-01 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_auto_20200228_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockhistory',
            options={'ordering': ['-created_at']},
        ),
    ]
